### ISSUE TITLE
.NET Standard supporting

### ISSUE THREAD

**Issue by navozenko** [navozenko/LinqSpecs#2]
There is an idea to add .NET Standard support to allow using LinqSpecs on the .NET Core. Unfortunately, the existing LinqSpecs code is not fully compatible with .NET Standard versions 1.0-1.6 because there is no SerializableAttribute in .NET Standard 1.0-1.6. All specifications in LinqSpecs are marked with the [Serializable] attribute and support binary serialization. Is it really necessary? Should we remove the [Serializable] attribute for compatibility with .NET Standard?

**Comment by navozenko** [comment]
Perhaps it makes sense to wait for .NET Standard 2.0

**Comment by ZOXEXIVO** [comment]
Maybe remove SpecSerizlization ? In 2k17 it's looks like legacy code

**Comment by navozenko** [comment]
@ZOXEXIVO
I thought about removing of serialization. But some developers need to transfer specifications to a server. So I think that in some kind serialization is needed. In addition, if we remove serialization it may be a serious violation of backwards compatibility for some users of LinqSpecs.

Unfortunately now AdHocSpecification serialization does not work satisfactorily (serialization of some elements of expression tree does not supported, for example, you can not serialize an expression containing null).

I see two solutions:
1. Correct the serialization of expression trees in LinqSpecs.
2. Use other NuGet packages for expression tree serialization.

I prefer the first option, and I'm trying to implement it gradually. Unfortunately this turned out to be a nontrivial task, and I have very little free time now, so the work is slow, I do not know how long it will take.

But why did you say that serialization looks like legacy code?

**Comment by navozenko** [comment]
@ZOXEXIVO
I thought about removing of serialization. But some developers need to transfer specifications to the server. So I think that in some version, serialization is needed. In addition, serialization removing may be a serious violation of backwards compatibility for some users of LinqSpecs.

Unfortunately now AdHocSpecification serialization does not work satisfactorily (serialization of some elements of expression trees is not supported, for example, you can not serialize an expression containing null).

I see two solutions:
1. Correct the serialization of expression trees and AdHocSpecification in LinqSpecs.
2. Use other NuGet packages for serialization.

I prefer the first option, and I'm trying to implement it gradually. Unfortunately this turned out to be a nontrivial task, and I have very little free time now, so the work is slow, I do not know how long it will take.

But why did you say that it's looks like legacy code?
